// Auto-generated by scripts/generate-test-data.mjs — do not edit by hand.
// Regenerate with: npm run test:report

export interface TestResult {
  describe: string
  title: string
  file: string
  status: 'passed' | 'failed' | 'skipped' | 'unknown'
  duration: number
  error?: string
  skipReason?: string
}

export interface TestRunMeta {
  generatedAt: string
  durationMs: number
  total: number
  passed: number
  failed: number
  skipped: number
}

export const testRunMeta: TestRunMeta = {
  "generatedAt": "2026-09-01T21:24:43.598Z",
  "durationMs": 80682,
  "total": 22,
  "passed": 21,
  "failed": 1,
  "skipped": 0
}

export const testResults: TestResult[] = [
  {
    "describe": "Seção de contato",
    "title": "botões de contato apontam para os canais corretos",
    "file": "contact.spec.ts",
    "status": "passed",
    "duration": 992
  },
  {
    "describe": "Seção de contato",
    "title": "link do LinkedIn abre em nova aba com rel seguro",
    "file": "contact.spec.ts",
    "status": "passed",
    "duration": 877
  },
  {
    "describe": "Seção de contato",
    "title": "barra de sugestão de disponibilidade tem CTA de e-mail",
    "file": "contact.spec.ts",
    "status": "passed",
    "duration": 917
  },
  {
    "describe": "Seção de contato",
    "title": "copiar e-mail para a área de transferência dá feedback visual",
    "file": "contact.spec.ts",
    "status": "passed",
    "duration": 976
  },
  {
    "describe": "Demonstração de estados",
    "title": "demonstração proposital: este teste falha para mostrar o estado \"falhou\" na suíte ao vivo",
    "file": "demo-failure.spec.ts",
    "status": "failed",
    "duration": 5823,
    "error": "Error: expect(locator).toBeVisible() failed\n\nLocator: getByText('Este texto não existe de propósito, para provar que a suíte relata falhas reais')"
  },
  {
    "describe": "Navegação desktop (sidebar)",
    "title": "clicar em um item da sidebar rola até a seção correspondente",
    "file": "navigation.spec.ts",
    "status": "passed",
    "duration": 1308
  },
  {
    "describe": "Navegação desktop (sidebar)",
    "title": "item ativo da sidebar muda conforme o scroll",
    "file": "navigation.spec.ts",
    "status": "passed",
    "duration": 1114
  },
  {
    "describe": "Navegação desktop (sidebar)",
    "title": "CTA \"Ver evidências\" do topo leva até a seção de projetos",
    "file": "navigation.spec.ts",
    "status": "passed",
    "duration": 1647
  },
  {
    "describe": "Navegação mobile (drawer)",
    "title": "drawer abre e fecha ao clicar no botão hambúrguer",
    "file": "navigation.spec.ts",
    "status": "passed",
    "duration": 696
  },
  {
    "describe": "Navegação mobile (drawer)",
    "title": "selecionar um item no drawer fecha o menu",
    "file": "navigation.spec.ts",
    "status": "passed",
    "duration": 869
  },
  {
    "describe": "Navegação mobile (drawer)",
    "title": "não há overflow horizontal em viewport mobile",
    "file": "navigation.spec.ts",
    "status": "passed",
    "duration": 565
  },
  {
    "describe": "Página principal",
    "title": "carrega com título e metadados corretos",
    "file": "portfolio.spec.ts",
    "status": "passed",
    "duration": 583
  },
  {
    "describe": "Página principal",
    "title": "visão geral exibe nome, cargo e stats",
    "file": "portfolio.spec.ts",
    "status": "passed",
    "duration": 569
  },
  {
    "describe": "Página principal",
    "title": "todas as seções principais estão presentes",
    "file": "portfolio.spec.ts",
    "status": "passed",
    "duration": 586
  },
  {
    "describe": "Página principal",
    "title": "histórico de progressão mostra as 4 etapas de carreira",
    "file": "portfolio.spec.ts",
    "status": "passed",
    "duration": 608
  },
  {
    "describe": "Página principal",
    "title": "experiência atual lista as responsabilidades da Pedbot",
    "file": "portfolio.spec.ts",
    "status": "passed",
    "duration": 612
  },
  {
    "describe": "Página principal",
    "title": "formação acadêmica aparece dentro da trajetória, concluída",
    "file": "portfolio.spec.ts",
    "status": "passed",
    "duration": 638
  },
  {
    "describe": "Página principal",
    "title": "exibe os 3 projetos técnicos em destaque",
    "file": "portfolio.spec.ts",
    "status": "passed",
    "duration": 607
  },
  {
    "describe": "Página principal",
    "title": "exibe os 4 grupos de competências técnicas",
    "file": "portfolio.spec.ts",
    "status": "passed",
    "duration": 650
  },
  {
    "describe": "Seção \"A suíte que testa este site\"",
    "title": "mostra 4 stat tiles com o resumo da última execução",
    "file": "tests-section.spec.ts",
    "status": "passed",
    "duration": 693
  },
  {
    "describe": "Seção \"A suíte que testa este site\"",
    "title": "painel de resultados detalhados fica oculto até uma execução ao vivo terminar",
    "file": "tests-section.spec.ts",
    "status": "passed",
    "duration": 666
  },
  {
    "describe": "Seção \"A suíte que testa este site\"",
    "title": "console de execução ao vivo degrada normalmente sem o backend",
    "file": "tests-section.spec.ts",
    "status": "passed",
    "duration": 739
  }
]
